debezium:
  name: entity-reference-embedded
  connector.class: io.debezium.connector.postgresql.PostgresConnector
  plugin.name: pgoutput
  database:
    hostname: ${PG_HOSTNAME}
    port: ${PG_PORT}
    user: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    dbname: ${PG_DBNAME}
    server.name: db
  slot.name: finu_slot
  publication.name: reference_publication
  table.include.list:
    - finance.accounts
    - finance.categories
    - finance.contractors
    - finance.companies
    - finance.groups
    - finance.group_values
  key.converter.schemas.enable: false
  value.converter.schemas.enable: false
  topic.prefix: finu
  offset.storage: org.apache.kafka.connect.storage.KafkaOffsetBackingStore
  offset.storage.topic: entity_reference_embedded_offset_storage
  offset.storage.partitions: 1
  offset.storage.replication.factor: 1
kafka:
  bootstrap-servers: localhost:9092
